### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [relastle/eucalyptus#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose one.

**Comment by relastle** [comment]
It is a great honor to be invited to such a nice curation repository.

I added MIT license, so please check it.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/720
